[window]
opacity = 0.4

[colors.primary]
background = "#13131D"
foreground = "#c8c8c8"
dim_foreground = "#a1a2a7"
bright_foreground = "#c8c8c8"

[colors.cursor]
text = "#13131D"
cursor = "#EA90A8"

[colors.vi_mode_cursor]
text = "#13131D"
cursor = "#EA90A8"

[colors.search.matches]
foreground = "#13131D"
background = "#a1a2a7"

[colors.search.focused_match]
foreground = "#13131D"
background = "#a6b2c7"

[colors.footer_bar]
foreground = "#13131D"
background = "#a1a2a7"

[colors.hints.start]
foreground = "#13131D"
background = "#D18BA2"

[colors.hints.end]
foreground = "#13131D"
background = "#a1a2a7"

[colors.selection]
text = "#13131D"
background = "#EA90A8"

[colors.normal]
black = "#13131D"
red = "#EA90A8"
green = "#a6b2c7"
yellow = "#D18BA2"
blue = "#7c7ca8"
magenta = "#9f859f"
cyan = "#919ab7"
white = "#a1a2a7"

[colors.bright]
black = "#434353"
red = "#f6bfce"
green = "#d1d9e4"
yellow = "#e3aebf"
blue = "#bcbcd4"
magenta = "#bfadbf"
cyan = "#d2d7e3"
white = "#c8c8c8"

[[colors.indexed_colors]]
index = 16
color = "#EA90A8"

[[colors.indexed_colors]]
index = 17
color = "#f6bfce"
